### ISSUE TITLE
Media Queries added , create responsive.css file

### ISSUE THREAD

**Issue by errinjohnson** [robrich22/wordgame#25]
Presentation

**Comment by errinjohnson** [comment]
Im working on this issue#25 along with issue#27.  they are related. errin

**Comment by JavidCode** [comment]
I added some responsiveness w/ media query.

**Comment by errinjohnson** [comment]
Hi Jvaid , just let me know if you are working on something ive already commit to.  I dont have notices to let me know when you are also working on the same thing.  thank you errin

**Comment by JavidCode** [comment]
Ok well I did it and it works, so don't worry about it.

**Comment by JavidCode** [comment]
See->http://htmlpreview.github.io/?https://raw.githubusercontent.com/JavidCode/WordGame/master/wordgame.html

**Comment by JavidCode** [comment]
If anything build off of what I've done.

**Comment by errinjohnson** [comment]
Jvaid, I Dont appreciate your tone, but will work with it anyway.

**Comment by JavidCode** [comment]
Sorry I'm just having a frustrating week, got some personal stuff going on, I apologize.
