### ISSUE TITLE
move javascript to external file

### ISSUE THREAD

**Issue by robrich502** [robrich22/wordgame#9]

**Comment by robrich502** [comment]
The javascript functions can go in one file and put the states and hints in a seperate javascript file.

**Comment by errinjohnson** [comment]
I was just thinking this would clean up the code a lot...i will create a feature branch javasciptFunc_file for now.  Then create a feature branch javascriptHint_file.  Then work on those branched.  Let me know if you need me to change this thought process, to align with the main project.
